# Generated by Django 4.0.1 on 2023-07-10 17:50

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_match_threshold', models.FloatField(default=0.4)),
                ('lev_score_threshold', models.IntegerField(default=80)),
                ('model_name', models.CharField(choices=[('Facenet', 'Facenet'), ('Facenet512', 'Facenet512'), ('OpenFace', 'OpenFace'), ('DeepID', 'DeepID'), ('ArcFace', 'ArcFace'), ('SFace', 'SFace')], default='VGG-Face', max_length=100)),
                ('metrics', models.CharField(choices=[('cosine', 'cosine'), ('euclidean', 'euclidean')], default='cosine', max_length=100)),
                ('backend', models.CharField(choices=[('opencv', 'opencv'), ('ssd', 'ssd'), ('dlib', 'dlib'), ('mtcnn', 'mtcnn'), ('retinaface', 'retinaface'), ('mediapipe', 'mediapipe')], default='opencv', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('found', 'found'), ('lost', 'lost')], default='Lost', max_length=100)),
                ('status', models.CharField(default='search', max_length=100)),
                ('main_cat', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_cat', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('c_state', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, to='core.Image')),
                ('matched_with', models.ManyToManyField(blank=True, to='core.Item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('msg', models.CharField(default='None', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_score', models.FloatField(default=0)),
                ('matching_score', models.FloatField(default=0)),
                ('founder_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('loster_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('face_matching_data', models.JSONField(blank=True, default=dict)),
                ('found_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='found_item', to='core.item')),
                ('lost_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_item', to='core.item')),
            ],
        ),
    ]
