# Generated by Django 4.0.1 on 2023-07-10 17:50

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('fname', models.CharField(blank=True, max_length=240, null=True)),
                ('lname', models.CharField(blank=True, max_length=240, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=240, null=True)),
                ('email_ac_timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_image_path)),
                ('is_google_user', models.BooleanField(default=False)),
                ('google_profile_img', models.CharField(blank=True, max_length=240, null=True)),
                ('google_id', models.CharField(blank=True, max_length=240, null=True)),
                ('is_mfa', models.BooleanField(default=False)),
                ('is_mfa_code_sent', models.BooleanField(default=False)),
                ('mfa_code', models.CharField(blank=True, max_length=6, null=True)),
                ('mfa_code_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
